//Nome: Eduardo Pereira Baratera - RA:2269104
package com.mycompany.projeto;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eduardo
 */
public class Menu extends javax.swing.JFrame {

    private static Menu MenuUnico;
    
    private Menu() {
        initComponents();
    }
    
    public static Menu getMenu(){
        if(MenuUnico == null){
            MenuUnico = new Menu();
        }
        return MenuUnico;
    }
    
    private DadosCart dbC = new DadosCart(); 
    private DadosTab dbT = new DadosTab();
    private Cartas cartas = new Cartas();
    private Tabuleiro tabuleiro = new Tabuleiro();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rtMenuP = new javax.swing.JLabel();
        btMenuCart = new javax.swing.JButton();
        btMenuTab = new javax.swing.JButton();
        btBuscasTab = new javax.swing.JButton();
        btBuscasCart = new javax.swing.JButton();
        rtResult = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbResults = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        rtMenuP.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        rtMenuP.setForeground(new java.awt.Color(255, 255, 255));
        rtMenuP.setText("MENU ");

        btMenuCart.setText("Busca de somente nomes de jogos de cartas");
        btMenuCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuCartActionPerformed(evt);
            }
        });

        btMenuTab.setText("Busca de somente nomes de jogos de tabuleiro");
        btMenuTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuTabActionPerformed(evt);
            }
        });

        btBuscasTab.setText("Buscas com filtros de tabuleiro");
        btBuscasTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscasTabActionPerformed(evt);
            }
        });

        btBuscasCart.setText("Buscas com filtros de cartas");
        btBuscasCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscasCartActionPerformed(evt);
            }
        });

        rtResult.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rtResult.setForeground(new java.awt.Color(255, 255, 255));
        rtResult.setText("RESULTADOS:");

        tbResults.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        tbResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nome do jogo:"
            }
        ));
        jScrollPane2.setViewportView(tbResults);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rtResult)
                .addGap(137, 137, 137))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(rtMenuP)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btMenuTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btMenuCart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btBuscasTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btBuscasCart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rtMenuP, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rtResult)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btMenuCart)
                        .addGap(18, 18, 18)
                        .addComponent(btMenuTab)
                        .addGap(18, 18, 18)
                        .addComponent(btBuscasTab, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btBuscasCart))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(167, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btMenuTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuTabActionPerformed
        exibirTdsT();
    }//GEN-LAST:event_btMenuTabActionPerformed

    private void btBuscasCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscasCartActionPerformed
        MBuscaCart.getMbuscaCart().setVisible(true);
    }//GEN-LAST:event_btBuscasCartActionPerformed

    private void btMenuCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuCartActionPerformed
        exibirTdsC();
    }//GEN-LAST:event_btMenuCartActionPerformed

    private void btBuscasTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscasTabActionPerformed
        MBuscaTab.getMbuscaTab().setVisible(true);
    }//GEN-LAST:event_btBuscasTabActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    private void exibirTdsC(){
        dbC.insere();
        DefaultTableModel tabelaMod = (DefaultTableModel) tbResults.getModel();
        tabelaMod.setRowCount(0);
        int pos = 0;
        for(Cartas cart: dbC.getList()){
            tabelaMod.insertRow(pos,new Object[]{cart.getNome()});
            pos++;
        }
        dbC.getList().clear();
    }
    private void exibirTdsT(){
        dbT.insere();
        DefaultTableModel tabelaMod = (DefaultTableModel) tbResults.getModel();
        tabelaMod.setRowCount(0);
        int pos = 0;
        for(Tabuleiro tabs: dbT.getList()){
            tabelaMod.insertRow(pos,new Object[]{tabs.getNome()});
            pos++;
        }
        dbT.getList().clear();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscasCart;
    private javax.swing.JButton btBuscasTab;
    private javax.swing.JButton btMenuCart;
    private javax.swing.JButton btMenuTab;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel rtMenuP;
    private javax.swing.JLabel rtResult;
    private javax.swing.JTable tbResults;
    // End of variables declaration//GEN-END:variables
}
